PREFIX maze: <https://kaefer3000.github.com/2021-02-dagstuhl/vocab#>

SELECT DISTINCT *
WHERE {
 ?x <http://www.w3.org/1999/xhtml/vocab#start> ?start .

 ?start maze:path ?r1 .
 ?r1 maze:path ?r2 .
 ?r2 maze:path ?r3 .
 ?r3 maze:path ?r4 .
 ?r4 maze:path ?r5 .
 ?r5 maze:path ?r6 .
 ?r6 maze:path ?r7 .
 ?r7 maze:path ?r8 .
 ?r8 maze:path ?r9 .
 ?r9 maze:path ?r10 .
 ?r10 maze:exit ?exit .
}